name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Ensure lock file exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found! Running npm install..."
            npm install --package-lock-only
            git add package-lock.json
            git commit -m "Generate package-lock.json in CI"
          fi

      - name: Install dependencies
        run: npm ci || npm install  # Use npm ci if possible, otherwise fallback to npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome

      - name: Upload Cypress test results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
